<?php

require_once 'DT/Time.php';

/**
 * Test class for DT_Time.
 * Generated by PHPUnit on 2012-06-12 at 14:08:21.
 */
abstract class AbstractDT_TimeTest extends PHPUnit_Framework_TestCase {
    public abstract function testGet();

    public abstract function testSet();

    public abstract function testSetAll();

    public abstract function testAdd();

    public abstract function testCompareTo();

    public abstract function testFormat();

    public abstract function testEquals();

    public abstract function testBefore();

    public abstract function testAfter();

    public abstract function testFormatTime();
}

?>